name = "concillio"
pages_build_output_dir = "./dist"

compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_AUDIT_RETENTION_HOURS = "24"
ADMIN_ERROR_BADGE_THRESHOLD = "3"
ANALYTICS_RETENTION_DAYS = "90"
AUDIT_HMAC_KEY = "__PAGES_SECRET__"
DATA_RETENTION_DAYS = "30"
HEURISTICS_CAP = "0.25"
HEURISTICS_ENABLED = "true"
HEURISTICS_MAX_HITS = "3"
HEURISTICS_PER_ROLE_MAX = "0.15"
PROMPT_KMS_ACTIVE_VERSION = "1"

[[kv_namespaces]]
binding = "AUDIT_LOG_KV"
id = "61dbc30846444bdc9c855a016cf43e51"

[[kv_namespaces]]
binding = "FLAGS_KV"
id = "0b02f6a9878e43a9a8aafd0c567f0d30"
preview_id = "d7dc6ff5722145cd8e3d08c8a22be4d0"

[[kv_namespaces]]
binding = "RL_KV"
id = "e76aba9e8fda4024a4ac10cfae83e45a"

[[d1_databases]]
binding = "DB"
database_name = "concillio-production"
database_id = "c62e1f76-7864-4a6c-8fdb-0c097ca5d21e"

[env.production]
compatibility_date = "2025-09-16"
