name = "concillio"
pages_build_output_dir = "./dist"
compatibility_date = "2025-10-10"
compatibility_flags = ["nodejs_compat"]

# PATCH 1 — Bind D1 + KV (and optional future R2)
# NOTE: Replace the placeholder IDs with real resource IDs from Cloudflare dashboard/CLI.
# Local development is automatic via --local; only production IDs are required below.

[[d1_databases]]
# Production D1 database (create via: wrangler d1 create concillio-production)
binding = "DB"
database_name = "concillio-production"
# database_id should be set to the value returned by `wrangler d1 create`
# Example: database_id = "123e4567-e89b-12d3-a456-426614174000"
# Leave as placeholder until configured in the dashboard/CI
database_id = "REPLACE_WITH_PRODUCTION_D1_DATABASE_ID"

# KV namespaces
# Rate limit counters (used by rateLimit middleware)
[[kv_namespaces]]
binding = "RL_KV"
# Set both id and preview_id via `wrangler kv:namespace create concillio_RL_KV` (and with --preview)
id = "REPLACE_WITH_KV_ID_RL"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID_RL"

# Webhook deduplication store for Stripe webhooks
[[kv_namespaces]]
binding = "WEBHOOK_DEDUP"
id = "REPLACE_WITH_KV_ID_WEBHOOK"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID_WEBHOOK"

# Audit log KV for best-effort error traces
[[kv_namespaces]]
binding = "AUDIT_LOG_KV"
id = "REPLACE_WITH_KV_ID_AUDIT"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID_AUDIT"
