name: Cloudflare Access smoke test

on:
  push:
    branches: [ "main" ]          # Produktion
  pull_request:                   # Preview (PR)
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: access-smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview-smoke:
    if: github.event_name == 'pull_request'
    name: Preview (Access)
    runs-on: ubuntu-latest
    environment: preview
    env:
      BASE_URL: https://main.concillio.pages.dev
      # Dessa två secrets (med .access redan inlagt i ID:t) ska finnas på environment: preview
      CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
    steps:
      - name: Smoke test with Cloudflare Access headers
        run: |
          set -euo pipefail
          # Följ ev. 302 från /favicon.ico -> /static/favicon.ico
          curl -fS -L \
            -H "CF-Access-Client-Id: ${CF_ACCESS_CLIENT_ID}" \
            -H "CF-Access-Client-Secret: ${CF_ACCESS_CLIENT_SECRET}" \
            "${BASE_URL}/favicon.ico" \
            -o /dev/null
          # Direkt på statisk fil (ska bli 200)
          curl -fS \
            -H "CF-Access-Client-Id: ${CF_ACCESS_CLIENT_ID}" \
            -H "CF-Access-Client-Secret: ${CF_ACCESS_CLIENT_SECRET}" \
            "${BASE_URL}/static/favicon.ico" \
            -o /dev/null
      - name: Preview OK
        run: echo "Preview Access check OK"

  production-smoke:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: Production (Access)
    runs-on: ubuntu-latest
    environment: production
    env:
      BASE_URL: https://concillio.pages.dev
      # Dessa två secrets (med .access redan i ID:t) ska finnas på environment: production
      CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
    steps:
      - name: Smoke test with Cloudflare Access headers
        run: |
          set -euo pipefail
          curl -fS -L \
            -H "CF-Access-Client-Id: ${CF_ACCESS_CLIENT_ID}" \
            -H "CF-Access-Client-Secret: ${CF_ACCESS_CLIENT_SECRET}" \
            "${BASE_URL}/favicon.ico" \
            -o /dev/null
          curl -fS \
            -H "CF-Access-Client-Id: ${CF_ACCESS_CLIENT_ID}" \
            -H "CF-Access-Client-Secret: ${CF_ACCESS_CLIENT_SECRET}" \
            "${BASE_URL}/static/favicon.ico" \
            -o /dev/null
      - name: Production OK
        run: echo "Production Access check OK"