name: Auto STATUS bump on green smoke

on:
  workflow_run:
    workflows: ["E2E Smoke on main"]
    types: [completed]

jobs:
  bump:
    # Kör endast om:
    # - workflow-run var success
    # - eventet kommer inte från PR (dvs. körning på main)
    # - käll-repot är detsamma (inte en fork)
    # - head_branch är 'main'
    if: |
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event != 'pull_request' &&
        github.event.workflow_run.head_repository.full_name == github.repository &&
        github.event.workflow_run.head_branch == 'main'
      }}
    runs-on: ubuntu-latest
    concurrency:
      group: auto-status-bump
      cancel-in-progress: false
    steps:
      - name: Dispatch "Update STATUS timestamp"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ADMIN_TOKEN }}   # PAT med repo-rättigheter
          event-type: update-status-timestamp
          # (optional) skicka lite metadata för spårbarhet
          client-payload: >-
            {
              "source_workflow": "${{ github.event.workflow_run.name }}",
              "run_id": "${{ github.event.workflow_run.id }}",
              "sha": "${{ github.event.workflow_run.head_sha }}"
            }
