name: Auto STATUS bump on green smoke

on:
  workflow_run:
    workflows: ["E2E Smoke on main"]
    types: [completed]

permissions: {}

jobs:
  bump:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_repository.full_name == github.repository &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch "Update STATUS timestamp"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          event-type: update-status-timestamp
          client-payload: '{"source":"auto-status-bump","run_id":"${{ github.run_id }}"}'

      # Fallback: trigga samma workflow via workflow_dispatch (filväg) på main
      - name: Fallback dispatch via Actions API (workflow_dispatch)
        if: always()
        uses: peter-evans/workflow-dispatch@v3
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          workflow: .github/workflows/status-timestamp.yml
          ref: main
