name: CI hygiene – Actions pinned

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]
    # Viktigt: ingen 'paths:'-begränsning – annars triggas inte hygienen på “vanliga” PR:ar.
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  hygiene:
    name: CI hygiene – Actions pinned / verify-actions-are-v4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute changed workflow files (PR only)
        id: changed
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          set -euo pipefail
          git fetch --no-tags --depth=1 origin "${{ github.base_ref }}"
          # OBS: globs får INTE vara i citat, annars matchar inte git diff pathspecs.
          CHANGED="$(git diff --name-only origin/${{ github.base_ref }}...HEAD -- .github/workflows/*.yml .github/workflows/*.yaml || true)"
          echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Fast-path when no workflow files changed (PR only)
        if: ${{ github.event_name == 'pull_request' && steps.changed.outputs.changed == '' }}
        run: echo "No workflow changes in PR – passing hygiene quickly."

      - name: Verify actions/* use @v4+ (no v1/v2/v3)
        if: ${{ github.event_name != 'pull_request' || steps.changed.outputs.changed != '' }}
        shell: bash
        run: |
          set -euo pipefail
          # Lista endast workflow-filer ur index (tål del-checkouts)
          mapfile -t FILES < <(git ls-files -- .github/workflows/*.yml .github/workflows/*.yaml || true)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No workflow files found."
            exit 0
          fi
          # Tillåt endast actions/* @v4+ (blocka v1/v2/v3)
          if grep -RInE 'uses:\s*actions/[a-zA-Z0-9_.-]+@v(1|2|3)(\b|[^0-9])' "${FILES[@]}" ; then
            echo "::error::Found actions/* pinned to @v1/@v2/@v3. Please bump to @v4."
            exit 1
          fi
          echo "OK: All actions/* are @v4 or higher."
