name: CI hygiene – Actions pinned

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]
    # Viktigt: ingen 'paths:'-begränsning – annars triggas inte hygienen på “vanliga” PR:ar.
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  verify-actions-are-v4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify all actions use @v4+ (no v1/v2/v3)
        shell: bash
        run: |
          set -euo pipefail
          # Sök bara i workflow-filer
          files=$(git ls-files '.github/workflows/*.yml' '.github/workflows/*.yaml')
          echo "$files" | xargs -r grep -nE 'uses:\s*[^@]+@v(1|2|3)\b' && {
            echo "::error::Found actions pinned to @v1/@v2/@v3. Please bump to @v4+."
            exit 1
          }
          echo "All actions are pinned to @v4+ ✅"
