name: CI hygiene – Actions pinned

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]
    # Viktigt: ingen 'paths:'-begränsning – annars triggas inte hygienen på “vanliga” PR:ar.
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  hygiene:
    name: CI hygiene – Actions pinned / verify-actions-are-v4
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Compute changed workflow files (PR only)
        if: github.event_name == 'pull_request'
        id: changed
        shell: bash
        run: |
          set -euo pipefail
          # Robust diff med eventets base/head-SHA (oberoende av HEAD/merge-läge)
          BASE="${{ github.event.pull_request.base.sha }}"
          HEADSHA="${{ github.event.pull_request.head.sha }}"
          # Fallback om nåt ovanför saknas (ska inte ske, men skadar inte)
          git fetch --no-tags --depth=1 origin "${{ github.base_ref }}" || true
          CHANGED="$(git diff --name-only "${BASE}" "${HEADSHA}" -- .github/workflows/*.yml .github/workflows/*.yaml || true)"
          if [ -n "$CHANGED" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Fast-path when no workflow files changed (PR only)
        if: github.event_name == 'pull_request' && steps.changed.outputs.has_changes == 'false'
        run: |
          echo "No workflow changes in PR – hygiene OK."

      - name: Verify actions/* use @v4+ (no v1/v2/v3)
        # Kör alltid på push; i PR bara om workflows ändrats
        if: github.event_name != 'pull_request' || steps.changed.outputs.has_changes == 'true'
        shell: bash
        run: |
          set -euo pipefail
          # Kör grep säkert med null-separerad fil-lista (tål mellanslag)
          mapfile -d '' FILES < <(git ls-files -z -- .github/workflows/*.yml .github/workflows/*.yaml || true)
          if [ "${#FILES[@]}" -eq 0 ]; then
            echo "No workflow files found."
            exit 0
          fi
          # Flagga ENDAST första-parts actions/* som ligger på @v1/@v2/@v3 (kräv v4+)
          # Hyphen placeras sist i klassen (ingen escape behövs).
          # Använder POSIX [:alnum:] och fast C-locale för grep.
          if printf '%s\0' "${FILES[@]}" \
            | LC_ALL=C xargs -0 grep -RInE 'uses:\s*actions/[[:alnum:]_.-]+@v(1|2|3)\b' -- ; then
            echo "::error title=Found old Actions versions (v1/v2/v3)::Please bump all actions/* usages to @v4 or higher."
            exit 1
          fi
          echo "OK: All actions/* are @v4 or higher."
