name: CI hygiene – Actions pinned

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]
    # Viktigt: ingen 'paths:'-begränsning – annars triggas inte hygienen på “vanliga” PR:ar.
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  hygiene:
    name: CI hygiene – Actions pinned / verify-actions-are-v4
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute changed workflow files (PR only)
        if: github.event_name == 'pull_request'
        id: changed
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin "${{ github.base_ref }}"
          CHANGED="$(git diff --name-only "origin/${{ github.base_ref }}"...HEAD -- .github/workflows/*.yml .github/workflows/*.yaml || true)"
          if [ -n "$CHANGED" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Fast-path when no workflow files changed (PR only)
        if: github.event_name == 'pull_request' && steps.changed.outputs.has_changes == 'false'
        run: |
          echo "No workflow changes in PR – hygiene OK."

      - name: Verify actions/* use @v4+ (no v1/v2/v3)
        # Kör alltid på push; i PR bara om workflows ändrats
        if: github.event_name != 'pull_request' || steps.changed.outputs.has_changes == 'true'
        shell: bash
        run: |
          set -euo pipefail
          # Lista endast workflow-filer
          FILES="$(git ls-files -- .github/workflows/*.yml .github/workflows/*.yaml || true)"
          if [ -z "$FILES" ]; then
            echo "No workflow files found."
            exit 0
          fi
          # Flagga ENDAST första-parts actions/* som ligger på @v1, @v2 eller @v3 (inkl v0)
          if grep -RInE 'uses:\s*actions/[A-Za-z0-9_.-]+@v(0|1|2|3)\b' ${FILES}; then
            echo "::error title=Found old Actions versions (v1/v2/v3)::Please bump all actions/* usages to @v4 or higher."
            exit 1
          fi
          echo "OK: All actions/* are @v4 or higher."
