name: CI hygiene – Actions pinned

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]
    # Viktigt: ingen 'paths:'-begränsning – annars triggas inte hygienen på “vanliga” PR:ar.
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  verify-actions-are-v4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # PR-optimering: räkna ut om några workflowfiler ändrats
      - name: Compute changed workflow files (PR only)
        if: github.event_name == 'pull_request'
        id: changed
        shell: bash
        run: |
          set -euo pipefail
          git fetch --no-tags --depth=1 origin "${{ github.base_ref }}"
          CHANGED="$(git diff --name-only "origin/${{ github.base_ref }}"...HEAD -- \
            '.github/workflows/*.yml' '.github/workflows/*.yaml' || true)"
          echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"

      # Fast-path: om inga workflowfiler ändrats i PR:n, markera grönt snabbt
      - name: Fast-path (no workflow changes)
        if: github.event_name == 'pull_request' && steps.changed.outputs.changed == ''
        run: echo "No workflow changes in PR; hygiene passes ✅"

      # Själva kontrollen – endast första-partsactions 'actions/*' måste vara @v4+
      - name: Verify actions/* use @v4+ (no v1/v2/v3)
        # Kör alltid på push; i PR kör vi bara om workflowfiler ändrats
        if: github.event_name != 'pull_request' || steps.changed.outputs.changed != ''
        shell: bash
        run: |
          set -euo pipefail
          # Lista workflowfiler robust; hantera fallet med 0 filer
          mapfile -t files < <(git ls-files ".github/workflows/*.yml" ".github/workflows/*.yaml" || true)
          if [ "${#files[@]}" -eq 0 ]; then
            echo "No workflow files found; nothing to check."
            exit 0
          fi
          # Matcha ENDAST första-partsactions: uses: actions/<name>@v1|v2|v3
          if grep -HnE 'uses:\s*actions/[A-Za-z0-9_.-]+@v(1|2|3)\b' "${files[@]}"; then
            echo "::error::Found first-party actions (actions/*) pinned to @v1/@v2/@v3. Please bump to @v4+."
            exit 1
          fi
          echo "OK: all actions/* are pinned to @v4+ ✅"
