name: Auto-merge Dependabot (patch/minor)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

jobs:
  automerge:
    # Kör ENDAST på Dependabot-PR:er i samma repo
    if: github.actor == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2

      - name: Enable auto-merge for safe updates (patch/minor)
        if: |
          steps.meta.outputs.update-type == 'version-update:semver-patch' ||
          steps.meta.outputs.update-type == 'version-update:semver-minor'
        uses: actions/github-script@v8
        with:
          script: |
            const q = `
            mutation($pr: ID!, $method: PullRequestMergeMethod!) {
              enablePullRequestAutoMerge(input: { pullRequestId: $pr, mergeMethod: $method }) {
                clientMutationId
              }
            }`;
            await github.graphql(q, {
              pr: context.payload.pull_request.node_id,
              method: "SQUASH",
            });
