name: Auto-merge Dependabot (patch/minor)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review, labeled]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    # Endast Dependabot, och endast PR:ar från samma repo (inte forks)
    if: >
      ${{
        github.actor == 'dependabot[bot]' &&
        github.event.pull_request.head.repo.full_name == github.repository
      }}
    runs-on: ubuntu-latest
    concurrency:
      group: automerge-dependabot-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for safe updates
        if: |
          (
            steps.meta.outputs.update-type == 'version-update:semver-minor' ||
            steps.meta.outputs.update-type == 'version-update:semver-patch'
          ) && (
            steps.meta.outputs.package-ecosystem == 'npm' ||
            steps.meta.outputs.package-ecosystem == 'github-actions'
          )
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request
            // Slå på auto-merge (respekterar branch protection & reviews)
            await github.graphql(`
              mutation($prId: ID!, $method: PullRequestMergeMethod!) {
                enablePullRequestAutoMerge(
                  input: { pullRequestId: $prId, mergeMethod: $method }
                ) { clientMutationId }
              }
            `, { prId: pr.node_id, method: "SQUASH" })
