name: Auto-merge Dependabot (patch/minor)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

jobs:
  automerge:
    # Kör ENDAST på Dependabot-PR:er i samma repo
    if: github.actor == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2

      - name: Enable auto-merge for safe updates (patch/minor)
        if: |
          github.actor == 'dependabot[bot]' &&
          contains(fromJson('["version-update:semver-patch","version-update:semver-minor"]'), steps.meta.outputs.update-type)
        uses: actions/github-script@v8
        with:
          script: |
            const q = `
              mutation Enable($pullRequestId: ID!, $mergeMethod: PullRequestMergeMethod!) {
                enablePullRequestAutoMerge(
                  input: { pullRequestId: $pullRequestId, mergeMethod: $mergeMethod }
                ) { clientMutationId }
              }
            `;
            await github.graphql(q, {
              pullRequestId: context.payload.pull_request.node_id,
              mergeMethod: "SQUASH"
            });
