name: E2E: Billing link visible
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  e2e_billing_link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Unit: menu.js DOM toggle
        run: npx vitest run --environment=jsdom tests/menu.billing-link.dom.spec.ts
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: E2E: Billing link visible
        env:
          BASE_URL: https://concillio.pages.dev
        run: npm run test:e2e
