name: Configure branch protection (main)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Protect "main" (require preview JUnit check; allow Actions bypass)
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/main/protection \
            -f required_status_checks:='{"strict":true,"contexts":["E2E (preview) – Summary"]}' \
            -f enforce_admins:=true \
            -f required_pull_request_reviews:=null \
            -f restrictions:=null \
            -f allow_force_pushes:=false \
            -f allow_deletions:=false \
            -f block_creations:=false \
            -f required_linear_history:=false \
            -f lock_branch:=false \
            -f bypass_pull_request_allowances:='{"users":[],"teams":[],"apps":["github-actions"]}'

      - name: Verify "main" protection (read-back)
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          echo "::group::Branch protection (main)"
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/main/protection \
          | jq '{required_status_checks: .required_status_checks,
                  enforce_admins: .enforce_admins,
                  bypass_pull_request_allowances: .bypass_pull_request_allowances}'
          echo "::endgroup::"
      - name: Protect "status" (allow Actions bypass; no required checks)
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/status/protection \
            -f required_status_checks:=null \
            -f enforce_admins:=true \
            -f required_pull_request_reviews:=null \
            -f restrictions:=null \
            -f allow_force_pushes:=false \
            -f allow_deletions:=false \
            -f block_creations:=false \
            -f required_linear_history:=false \
            -f lock_branch:=false \
            -f bypass_pull_request_allowances:='{"users":[],"teams":[],"apps":["github-actions"]}'

      - name: Verify "status" protection (read-back)
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          echo "::group::Branch protection (status)"
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/status/protection \
          | jq '{required_status_checks: .required_status_checks,
                  enforce_admins: .enforce_admins,
                  bypass_pull_request_allowances: .bypass_pull_request_allowances}'
          echo "::endgroup::"