name: Configure branch protection (main)

on:
  workflow_dispatch:

permissions:
  contents: read
  administration: write

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Apply branch protection on main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          owner="${GITHUB_REPOSITORY%%/*}"
          repo="${GITHUB_REPOSITORY##*/}"

          echo "Setting branch protection for ${owner}/${repo}#main"

          curl -sS -X PUT \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${owner}/${repo}/branches/main/protection" \
            -d @- <<'JSON'
          {
            "required_status_checks": {
              "strict": true,
              "contexts": [
                "E2E (preview) – Summary",
                "E2E Smoke on main – Summary"
              ]
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "required_approving_review_count": 1
            },
            "restrictions": null
          }
          JSON

          echo "Branch protection applied."
