name: Configure branch protection (main)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Apply branch protection on main
        env:
          # Fine-grained PAT med repo-admin (lägg den som repo/org secret)
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          # JSON-kroppen som krav (lägg märke till exakt check-namn med en-dash)
          BODY: |
            {
              "required_status_checks": {
                "strict": true,
                "contexts": [
                  "E2E (preview) – Summary"
                ]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": true,
                "required_approving_review_count": 0
              },
              "bypass_pull_request_allowances": {
                "users": [],
                "teams": [],
                "apps": ["github-actions"]
              },
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false,
              "block_creations": false,
              "required_linear_history": false,
              "lock_branch": false
            }
        run: |
          set -euo pipefail
          owner="${GITHUB_REPOSITORY%/*}"
          repo="${GITHUB_REPOSITORY#*/}"

          echo "Setting branch protection for ${owner}/${repo}@main"

          curl -sSf -X PUT \
            -H "Authorization: Bearer ${ADMIN_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            --data "${BODY}" \
            "https://api.github.com/repos/${owner}/${repo}/branches/main/protection"

          echo "Branch protection applied."
