name: E2E Smoke on main

on:
  push:
    branches: [ "main" ]

concurrency:
  group: pages-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-matrix:
    name: E2E Smoke – ${{ matrix.browser }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    env:
      BASE_URL: ${{ secrets.SMOKE_BASE_URL }}
      CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID_SMOKE }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET_SMOKE }}
      TEST_LOGIN_TOKEN: ${{ secrets.TEST_LOGIN_TOKEN }}
      JUNIT_FILE: junit/junit-${{ matrix.browser }}.xml
      PLAYWRIGHT_HTML_REPORT: playwright-report-${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - name: Access preflight (HEAD)
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}\n" -I \
            -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID_SMOKE" \
            -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET_SMOKE" \
            "${SMOKE_BASE_URL}")
          if [ "$code" != "200" ] && [ "$code" != "204" ]; then
            echo "Access preflight failed ($code)"; exit 1
          fi
        env:
          CF_ACCESS_CLIENT_ID_SMOKE:    ${{ secrets.CF_ACCESS_CLIENT_ID_SMOKE }}
          CF_ACCESS_CLIENT_SECRET_SMOKE:${{ secrets.CF_ACCESS_CLIENT_SECRET_SMOKE }}
          SMOKE_BASE_URL:               ${{ secrets.SMOKE_BASE_URL }}
      - run: npx playwright install --with-deps
      - name: Run Playwright (${{ matrix.browser }})
        run: npx playwright test --project=${{ matrix.browser }} --config=tests/e2e/playwright.config.ts
      - name: Upload JUnit (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.browser }}
          path: ${{ env.JUNIT_FILE }}
          retention-days: 7

  junit-summary:
    name: E2E Smoke on main – Summary
    needs: e2e-matrix
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: junit-*
          path: junit-merged
      - name: Publish JUnit summary (main)
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'junit-merged/**.xml'
          check_name: 'E2E Smoke on main'
          require_tests: true
          include_passed: true
          detailed_summary: true
