name: E2E Smoke on main

on:
  push:
    branches: [ "main" ]

jobs:
  e2e-matrix:
    name: E2E Smoke – ${{ matrix.browser }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    env:
      BASE_URL: ${{ secrets.SMOKE_BASE_URL }}
      JUNIT_FILE: junit/junit-${{ matrix.browser }}.xml
      PLAYWRIGHT_HTML_REPORT: playwright-report-${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run Playwright (${{ matrix.browser }})
        run: npx playwright test --project=${{ matrix.browser }} --config=tests/e2e/playwright.config.ts
      - name: Upload JUnit (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.browser }}
          path: ${{ env.JUNIT_FILE }}
          retention-days: 7

  junit-summary:
    name: E2E Smoke on main – Summary
    needs: e2e-matrix
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: junit-*
          path: junit-merged
      - name: Publish JUnit summary (main)
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'junit-merged/**.xml'
          check_name: 'E2E Smoke on main'
          require_tests: true
          include_passed: true
          detailed_summary: true
