name: E2E Smoke on main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  # Set in repo secrets: SMOKE_BASE_URL = https://smoke.concillio.pages.dev (or your custom smoke domain)
  BASE_URL: ${{ secrets.SMOKE_BASE_URL }}

jobs:
  e2e-smoke-main:
    name: E2E Smoke on main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Echo env (masked secrets)
        run: |
          if [ -z "$BASE_URL" ]; then echo "BASE_URL is NOT set" && exit 1; fi
          echo "BASE_URL is set"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E smoke (main)
        run: npx playwright test --config=tests/e2e/playwright.config.ts

      - name: Upload JUnit (smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-smoke
          path: junit/*.xml
          retention-days: 7
