name: E2E Smoke on main

permissions:
  contents: read
  deployments: write
  statuses: write
  checks: write

on:
  push:
    branches: [ main ]

concurrency:
  group: pages-prod-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20

jobs:
  e2e:
    name: E2E Smoke (main)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    env:
      BASE_URL:               ${{ secrets.SMOKE_BASE_URL }}
      CF_ACCESS_CLIENT_ID:     ${{ secrets.CF_ACCESS_CLIENT_ID_SMOKE }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET_SMOKE }}
      TEST_LOGIN_TOKEN:        ${{ secrets.TEST_LOGIN_TOKEN }}
      JUNIT_FILE:              junit/junit-${{ matrix.browser }}.xml
      PLAYWRIGHT_HTML_REPORT:  playwright-report-${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v4

      - name: Locate project root (force repo root)
        id: root
        shell: bash
        run: |
          set -euo pipefail
          echo "root=." >> "$GITHUB_OUTPUT"
          echo "Using repo root as canonical Node project dir"

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ steps.root.outputs.root }}/package-lock.json

      - name: Install deps & browsers
        working-directory: ${{ steps.root.outputs.root }}
        run: |
          set -euo pipefail
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          npx playwright install --with-deps

      - name: Build
        working-directory: ${{ steps.root.outputs.root }}
        run: npm run build

      - name: Access preflight (HEAD + Location check, smoke)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          BASE_URL: ${{ secrets.SMOKE_BASE_URL }}
        shell: bash
        run: |
          set -euo pipefail

          # Normalisera trailing slash
          url="${BASE_URL%/}/"

          # 1) Oautentiserad HEAD mot login-endpoint (ingen header)
          #    Vi tillåter 301/302/303 så länge Location pekar på /cdn-cgi/access/login
          read -r code_ndhdr loc_ndhdr <<<"$(
            curl -sI "$url" | awk 'BEGIN{code="";loc=""} 
              /^HTTP\//{code=$2} 
              tolower($1)=="location:"{loc=$2} 
              END{printf "%s %s", code, loc}'
          )"

          if [[ "$code_ndhdr" =~ ^30[123]$ ]] && [[ "$loc_ndhdr" =~ ^/cdn-cgi/access/login ]]; then
            echo "Access preflight OK (unauth HEAD: $code_ndhdr → $loc_ndhdr)"
          else
            echo "Expected unauthenticated 30x → /cdn-cgi/access/login; got: $code_ndhdr $loc_ndhdr"
            exit 1
          fi

          # 2) Valfritt: snäll extra-koll att autentiserad HEAD inte fortsätter till login
          # (om ni vill – kan tas bort om onödig)
          # read -r code_hdr loc_hdr <<<"$(
          #   curl -sI "$url" \
          #     -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID_SMOKE }}" \
          #     -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET_SMOKE }}" \
          #   | awk 'BEGIN{code="";loc=""} /^HTTP\//{code=$2} tolower($1)=="location:"{loc=$2} END{printf "%s %s", code, loc}'
          # )"
          # if [[ "$code_hdr" =~ ^20[04]$ || -z "$loc_hdr" ]]; then
          #   echo "Access authenticated preflight OK ($code_hdr $loc_hdr)"
          # else
          #   echo "Unexpected redirect while authenticated: $code_hdr $loc_hdr"
          #   exit 1
          # fi

      - name: Run Playwright (${{ matrix.browser }})
        working-directory: ${{ steps.root.outputs.root }}
        env:
          BASE_URL:               ${{ secrets.SMOKE_BASE_URL }}
          CF_ACCESS_CLIENT_ID:     ${{ secrets.CF_ACCESS_CLIENT_ID_SMOKE }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET_SMOKE }}
          TEST_LOGIN_TOKEN:        ${{ secrets.TEST_LOGIN_TOKEN }}
        run: |
          set -euo pipefail
          CONFIG="$GITHUB_WORKSPACE/playwright.config.ts"
          echo "Using config: $CONFIG"
          ls -l "$CONFIG"
          npx playwright test tests/e2e/preview-validation.spec.ts \
            --project=${{ matrix.browser }} \
            --config="$CONFIG"

      - name: Upload JUnit (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.browser }}
          path: junit/junit-${{ matrix.browser }}.xml
          if-no-files-found: ignore

      - name: Upload HTML report (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report-${{ matrix.browser }}
          if-no-files-found: ignore

  junit-summary:
    name: E2E Smoke on main – Summary
    needs: e2e
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: junit-merged
      - uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'junit-merged/**/*.xml'
          check_name: 'E2E Smoke on main – Summary'
          fail_on_failure: false
          include_passed: true
