name: E2E Smoke on main

permissions:
  contents: read
  deployments: write
  statuses: write
  checks: write

on:
  push:
    branches: [ main ]

concurrency:
  group: pages-prod-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20

jobs:
  e2e:
    name: E2E Smoke (main)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    env:
      BASE_URL:               ${{ secrets.SMOKE_BASE_URL }}
      CF_ACCESS_CLIENT_ID:     ${{ secrets.CF_ACCESS_CLIENT_ID_SMOKE }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET_SMOKE }}
      TEST_LOGIN_TOKEN:        ${{ secrets.TEST_LOGIN_TOKEN }}
      JUNIT_FILE:              junit/junit-${{ matrix.browser }}.xml
      PLAYWRIGHT_HTML_REPORT:  playwright-report-${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v4

      - name: Locate project root (force repo root)
        id: root
        shell: bash
        run: |
          set -euo pipefail
          echo "root=." >> "$GITHUB_OUTPUT"
          echo "Using repo root as canonical Node project dir"

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ steps.root.outputs.root }}/package-lock.json

      - name: Install deps & browsers
        working-directory: ${{ steps.root.outputs.root }}
        run: |
          set -euo pipefail
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          npx playwright install --with-deps

      - name: Build
        working-directory: ${{ steps.root.outputs.root }}
        run: npm run build

      - name: Access preflight (HEAD + Location check, smoke)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          URL: ${{ secrets.SMOKE_BASE_URL }}
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID_SMOKE }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET_SMOKE }}
        shell: bash
        run: |
          set -euo pipefail

          url="$URL"

          # Följ upp till 2 hopp för att komma till effektiv URL (http->https, apex->www etc)
          mapfile -t hops < <(curl -sS -I --max-redirs 2 -o /dev/null -w '%{http_code}\n%{url_effective}\n' "$url")
          final="${hops[1]}"

          # Oautentiserad HEAD ska ge 301/302 redirect till /cdn-cgi/access/login
          code="$(curl -sS -I -o /dev/null -w '%{http_code}' "$final")"
          loc="$(curl -sS -I "$final" | awk '/^location:/I{print $2}' | tr -d "\r")"

          if [[ "$code" != "301" && "$code" != "302" ]]; then
            echo "Expected unauthenticated HEAD 301/302 to /cdn-cgi/access/login, got $code"
            exit 1
          fi
          if [[ ! "$loc" =~ /cdn-cgi/access/login ]]; then
            echo "Expected redirect to /cdn-cgi/access/login, got: $loc"
            exit 1
          fi

          # Autentiserad GET ska ge 200/204
          code="$(curl -sS -o /dev/null -w '%{http_code}' \
            -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" \
            -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" \
            "$final")"
          if [[ "$code" != "200" && "$code" != "204" ]]; then
            echo "Expected authenticated 200/204, got $code"
            exit 1
          fi

      - name: Run Playwright (${{ matrix.browser }})
        working-directory: ${{ steps.root.outputs.root }}
        env:
          BASE_URL:               ${{ secrets.SMOKE_BASE_URL }}
          CF_ACCESS_CLIENT_ID:     ${{ secrets.CF_ACCESS_CLIENT_ID_SMOKE }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET_SMOKE }}
          TEST_LOGIN_TOKEN:        ${{ secrets.TEST_LOGIN_TOKEN }}
        run: |
          set -euo pipefail
          CONFIG="$GITHUB_WORKSPACE/playwright.config.ts"
          echo "Using config: $CONFIG"
          ls -l "$CONFIG"
          npx playwright test tests/e2e/preview-validation.spec.ts \
            --project=${{ matrix.browser }} \
            --config="$CONFIG"

      - name: Upload JUnit (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.browser }}
          path: junit/junit-${{ matrix.browser }}.xml
          if-no-files-found: ignore

      - name: Upload HTML report (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report-${{ matrix.browser }}
          if-no-files-found: ignore

  junit-summary:
    name: E2E Smoke on main – Summary
    needs: e2e
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: junit-merged
      - uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'junit-merged/**/*.xml'
          check_name: 'E2E Smoke on main – Summary'
          fail_on_failure: false
          include_passed: true
