name: Update STATUS timestamp

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["E2E (preview)", "E2E Smoke on main"]
    types: [completed]

permissions:
  contents: write

jobs:
  update:
    if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare status branch
        run: |
          set -euo pipefail
          git checkout -B status
      - name: Update STATUS.md timestamp and status.json
        run: |
          ts=$(date -u +"%Y-%m-%d %H:%M UTC")
          sed -i "s/<!--STATUS_TS-->.*<!--\\/STATUS_TS-->/<!--STATUS_TS-->${ts}<!--\\/STATUS_TS-->/" STATUS.md || echo "<!--STATUS_TS-->${ts}<!--/STATUS_TS-->" >> STATUS.md
          printf '{"schemaVersion":1,"label":"status","message":"ok","color":"success","timestamp":"%s"}\n' "$ts" > status.json
      - name: Commit and push (status branch)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add STATUS.md status.json
          git commit -m "chore(status): update timestamp [skip ci]" || echo "No changes"
          git push -u origin status
