name: Update STATUS timestamp

permissions:
  contents: write
  actions: read
  pull-requests: read

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["E2E (preview)", "E2E Smoke on main"]
    types: [completed]

jobs:
  update:
    if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true
          fetch-depth: 0

      - name: Update STATUS.md timestamp + write status.json
        run: |
          set -euo pipefail
          TS="$(date -u +'%Y-%m-%d %H:%M UTC')"
          sed -i "s|<!--STATUS_TS-->.*<!--/STATUS_TS-->|<!--STATUS_TS-->${TS}<!--/STATUS_TS-->|" STATUS.md
          echo "{\"updated\":\"${TS}\"}" > status.json

      - name: Switch to 'status' branch (create if missing)
        run: |
          git fetch origin status || true
          if git ls-remote --exit-code --heads origin status >/dev/null 2>&1; then
            git checkout -B status origin/status
          else
            git checkout -B status
          fi
      - name: Commit + push [skip ci]
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add STATUS.md status.json
          git commit -m "docs: update STATUS timestamp + json [skip ci]" || echo "No changes"
          git push origin HEAD:status
