name: Update STATUS timestamp

on:
  workflow_run:
    workflows: ["E2E (preview)", "E2E Smoke on main"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: status-timestamp
  cancel-in-progress: true

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute timestamp (UTC)
        id: ts
        run: echo "ts=$(date -u +'%Y-%m-%d %H:%M UTC')" >> "$GITHUB_OUTPUT"

      - name: Update STATUS.md timestamp + write status.json
        run: |
          file="STATUS.md"
          ts='${{ steps.ts.outputs.ts }}'

          # Uppdatera raden i STATUS.md mellan markörerna
          perl -0777 -pe "s|(<!--STATUS_TS-->).*?(<!--/STATUS_TS-->)|$1${ts}$2|s" -i "$file"

          # Skriv JSON för badge
          printf '{ "updated": "%s" }\n' "${ts}" > status.json

      - name: Commit timestamp + JSON [skip ci]
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update STATUS timestamp + json [skip ci]"
          file_pattern: "STATUS.md status.json"
