name: Update STATUS timestamp

permissions:
  contents: write

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [update-status-timestamp]

jobs:
  bump:
    # inga extra guards behövs – endast manuellt eller via repository_dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true
          fetch-depth: 0

      # IMPORTANT: Switch to 'status' branch BEFORE editing files
      - name: Switch to 'status' branch (create if missing)
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin status || true
          if git ls-remote --exit-code --heads origin status >/dev/null 2>&1; then
            git checkout -B status origin/status
          else
            # Create status branch from current ref (main)
            git checkout -B status
          fi

      - name: Write TIMESTAMP, STATUS.md and Shields endpoint JSON
        shell: bash
        run: |
          set -euo pipefail
          TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          mkdir -p status

          # 1) Maskinläsbar tidsstämpel
          echo "$TS" > status/TIMESTAMP

          # 2) (valfri) status-sida för repo-visibility
          cat > STATUS.md <<'MD'
          # Concilio — Build & Deploy status
          Denna sida uppdateras automatiskt av `.github/workflows/status-timestamp.yml` efter lyckade CI-körningar (eller vid manuell körning).
          **Badge** läser från `status.json` på `status`-branchen.
          MD

          # 3) Shields endpoint enligt schemaVersion 1 (best practice)
          jq -n --arg ts "$TS" '{
            schemaVersion: 1,
            label: "deploy",
            message: ("ok (" + $ts + ")"),
            color: "green",
            cacheSeconds: 300
          }' > status/status.json

          # --- Safe commit via worktree (no branch switching / no history reset) ---
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 0) Samla output i en separat katalog så vi inte rör working tree innan worktree finns
          OUT="_status_out"
          rm -rf "$OUT"; mkdir -p "$OUT/status"
          cp -f status/TIMESTAMP "$OUT/status/TIMESTAMP"
          cp -f STATUS.md "$OUT/STATUS.md"
          cp -f status/status.json "$OUT/status/status.json"

          # 1) Skapa/återanvänd worktree för status-branchen
          WT="../status-worktree"
          rm -rf "$WT"
          if git ls-remote --exit-code origin status >/dev/null 2>&1; then
            # Branch finns på remote → checkout den i en worktree
            git worktree add -B status "$WT" origin/status
          else
            # Förstakörning: skapa ny branch i worktree
            git worktree add -b status "$WT"
          fi

          # 2) Kopiera in filer och committa
          rsync -a --delete "$OUT/STATUS.md" "$OUT/status/" "$WT"/
          pushd "$WT" >/dev/null
            git add STATUS.md status/TIMESTAMP status/status.json
            git commit -m "chore(status): update TIMESTAMP + shields endpoint" || echo "No changes to commit"
            git push origin status
          popd >/dev/null

          # 3) Städa worktree
          git worktree remove "$WT" --force
          rm -rf "$OUT"
