name: Update STATUS timestamp

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["E2E (preview)", "E2E Smoke on main"]
    types: [completed]

permissions:
  contents: write

jobs:
  update-status:
    runs-on: ubuntu-latest
    # Kör alltid vid workflow_dispatch. Vid workflow_run: bara när föregående workflow lyckades.
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update STATUS.md timestamp + write status.json
        shell: bash
        run: |
          ts="$(date -u +"%Y-%m-%d %H:%M UTC")"
          sed -i 's/<!--STATUS_TS-->.*<!--\/STATUS_TS-->/<!--STATUS_TS-->'"$ts"'<!--\/STATUS_TS-->/' STATUS.md
          printf '{"updated":"%s"}\n' "$ts" > status.json

      - name: Commit timestamp + JSON [skip ci]
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add STATUS.md status.json
          git commit -m "docs: update STATUS timestamp + json [skip ci]" || echo "No changes"
          git push
