name: Update STATUS timestamp

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["E2E (preview)", "E2E Smoke on main"]
    types: [completed]

permissions:
  contents: write

jobs:
  update:
    if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Compute UTC timestamp
        run: echo "TS=$(date -u +'%Y-%m-%d %H:%M UTC')" >> $GITHUB_ENV

      - name: Show marker BEFORE
        run: |
          echo "----- BEFORE -----"
          grep -n "STATUS_TS" STATUS.md || true
          ls -la || true
          git status -s || true

      - name: Write status.json (always changes)
        run: printf '{"updated":"%s"}\n' "$TS" > status.json

      - name: Update STATUS.md marker (robust)
        run: |
          perl -0777 -pe "s|<!--STATUS_TS-->.*?<!--/STATUS_TS-->|<!--STATUS_TS-->$ENV{TS}<!--/STATUS_TS-->|s" -i STATUS.md

      - name: Show marker AFTER & diff
        run: |
          echo "----- AFTER ------"
          grep -n "STATUS_TS" STATUS.md || true
          git diff -- STATUS.md status.json || true

      - name: Commit + push [skip ci]
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add STATUS.md status.json
          git commit -m "docs: update STATUS timestamp + json [skip ci]" || echo "No changes"
          git push
