name: Mirror from public Concillio

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # hourly

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add upstream remote and fetch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/ejob-ai/Concillio.git || git remote set-url upstream https://github.com/ejob-ai/Concillio.git
          git fetch upstream --prune
      - name: Reset to upstream/main
        run: |
          git checkout -B main
          git reset --hard upstream/main
      - name: Push to private main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin +main:main
